codecov:
  ci:
    - github.com

coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 1

ignore:
  - "**/*/dist/*.js"
  - "**/*.{spec,test}.js"
  - "**/*.eslintrc.js"

parsers:
  javascript:
    enable_partials: yes
