sudo: false

language: node_js

node_js:
  - "6"
  - "8"
  - "10"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install --ignore-engines

after_success:
  - yarn coverage

cache:
  yarn: true
  directories:
    - node_modules
